# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-12 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_date', models.DateTimeField()),
                ('title', models.CharField(max_length=40)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
    ]
